### ISSUE TITLE
Wrong alpha channel (?)

### ISSUE THREAD

**Issue by Rinnegatamante** [Rinnegatamante/easyrpg-player-3ds#1]
It seems sf2dlib has some kind of problem with alpha processing. For example the FPS Counter is blended as a full opaque rect without any text in it instead of a semi-transparent ones with a text inside.

**Comment by Cruel** [comment]
Try changing this to `PF::Alpha`

https://github.com/Rinnegatamante/easyrpg-player-3ds/blob/master/src/3ds_ui.cpp#L60

I could be wrong, but that's what my local repo has and I don't think I had transparency problems.

**Comment by Cruel** [comment]
I'm not sure which FPS counter you're talking about besides the one you added to console.

And I haven't tried, but I noticed my local repo has `PF::Alpha` on this line:

https://github.com/Rinnegatamante/easyrpg-player-3ds/blob/master/src/3ds_ui.cpp#L60

I could be wrong, but try changing that.

**Comment by Rinnegatamante** [comment]
If you press L, you should see an FPS counter.
Anyway the Bitmap Surface is set like in SDL wrapper as Ghabry told me to do: https://easy-rpg.org/forums/viewtopic.php?f=4&t=625

(Even using Alpha make the same problem happens at least for me).

**Comment by Rinnegatamante** [comment]
Solved with https://github.com/Rinnegatamante/easyrpg-player-3ds/commit/215ed5b6c3a8fc11e0ab5740ff2e29cd188954af
