### ISSUE TITLE
Trouble finding libraries

### ISSUE THREAD

**Issue by sorlok** [Rinnegatamante/easyrpg-player-3ds#13]
I'm having trouble building and finding the following libraries:

ld: cannot find -llcf
ld: cannot find -licuuc
ld: cannot find -licui18n
ld: cannot find -licudata
ld: cannot find -lpixman-1
ld: cannot find -lsvchax
ld: cannot find -lvorbisidec
ld: cannot find -logg

Did you cross-compile these for ARM yourself? Any chance of getting a "dependency pack" with the static libraries? (I really want to hack around with the Easy RPG source, instead of just fiddling with library building.)

**Comment by Rinnegatamante** [comment]
Here you can find libsvchax: https://github.com/Rinnegatamante/libsvchax
In this topic you can find the other portlibs: https://easy-rpg.org/forums/viewtopic.php?f=4&t=625&p=1568#p1568

**Comment by sorlok** [comment]
Thanks; I was able to compile it with the information you provided. :)
