### ISSUE TITLE
RomFS support (and .cia launching and stuff)

### ISSUE THREAD

**Issue by Ghabry** [Rinnegatamante/easyrpg-player-3ds#5]
Just providing some useful information that could be handy for this :)

The player uses the working directory to find games. BUT you can use the command line argument "--project-path" to change that search path if passing arguments is possible from .cia somehow, no idea.
If the project-path is not writable you can change the save path with "--save-path".
(All supported arguments: https://easy-rpg.org/wiki/user/player/command-line )

Of course you can also add extra logic to "Main_Data::Init" to detect situations like RomFS and just populate the project_path and save_path variables correctly (like we already do for Wii "GEKKO")

[The logic is: When save_path is empty, it uses the project_path]

**Comment by Rinnegatamante** [comment]
Added with https://github.com/Rinnegatamante/easyrpg-player-3ds/commit/ffb1c29421a69aec1e97a06201b5c8dfd78f540a
