### ISSUE TITLE
Can't boot on New 3ds

### ISSUE THREAD

**Issue by sorlok** [Rinnegatamante/easyrpg-player-3ds#6]
Running on a New 3DS, arm9loaderhax, firmware 10.7.0 (sysNAND), using the latest build (March 22, 2016, from the forum post).

Booting from the Homebrew menu, it goes directly to a red lower screen and hangs there forever. Tried multiple times.

**Comment by Rinnegatamante** [comment]
Looks like you're using a bad target with a too low code section.

**Comment by sorlok** [comment]
Hmm.... makes sense. But it doesn't even ask me to select a target ---does it just automatically use the cartridge in the slot at the time?

**Comment by Rinnegatamante** [comment]
It depends on the descriptor used.

**Comment by sorlok** [comment]
Ah, ok. I'll look into it. Thanks!

FYI, the game I was using was Zelda OOT 3D, in case there is a list of targets that "don't work".
