### ISSUE TITLE
Slow resources loading

### ISSUE THREAD

**Issue by Rinnegatamante** [Rinnegatamante/easyrpg-player-3ds#8]
At the moment resourced loading is pretty slow making game startup a real pain in the ass.

**Comment by Ghabry** [comment]
Did you already try linking with the new liblcf that I included in the toolchain I think a week ago?

**Comment by Rinnegatamante** [comment]
Yes, it seems to not solve the problem (or at least there are no significative speedups).

**Comment by Ghabry** [comment]
okay I'm out of ideas now. liblcf and the FileFinder were the only candidates for me.
Maybe memory allocation is not very fast, this would also heavily slow down the liblcf parsing. But this needs a custom "new"-allocator to test... ugh.

**Comment by Rinnegatamante** [comment]
Oh wait, looks like i was wrong and i was still using old liblcf (20/03/2016) instead of the latest one (23/03/2016).

Going to recompile it and try (it will require like 45 minutes, i hate my laptop PC sigh)

**Comment by Ghabry** [comment]
Use a Linux VM. GCC is much faster under Linux :/

**Comment by Rinnegatamante** [comment]
It's just the laptop that it's shitty (it's a 200€ laptop with a shitty CPU <.<).
On my desktop PC which is an assemebled gaming PC it compiles in few seconds but i'm not in my universitarian home so... laptop PC is my only choice.

As for Linux VM, i personally hate Linux and usually i try to use it less then i can.

**Comment by Rinnegatamante** [comment]
Ok tested right now and with this, system crashes after  A LOT of loading time (like 7 minutes for Yume Nikki) without even reaching BGM music startup.

P.S. I also need a download link for the old version since with this it doesn't start at all and i've not done a backup :/.

**Comment by Ghabry** [comment]
Does every game crash? At least TestGame should work, I tested this on Windows :/. Did you also **replace your liblcf headers** with the one in the archive? Because some of them had changed.

Ugh, recompiling will take a while because I lost the toolchain source files due to a server problem. Need at least 24h for this, sorry :/

**Comment by Rinnegatamante** [comment]
Replaced right now also header files and Yume Nikki still crashes after a couple of minutes of loading (maybe you forgot to free temp buffers used by liblcf? Dunno...). [Side note: I noticed that it crashes right after telling me that Game and Save folders are set to . , this is the log right after crashing so you can see also how much time it needs to load:

[2011-02-28 00:41:17] Debug: EasyRPG Player 0.4.1 started
[2011-02-28 00:41:17] Debug: ============================
[2011-02-28 00:41:17] Debug: CLI: 
[2011-02-28 00:41:17] Debug: Sound initialized successfully!
[2011-02-28 00:41:17] Debug: Starting BGM stream thread...
[2011-02-28 00:41:18] Debug: Initializing sound cache (Dim: 5242880 bytes)
[2011-02-28 00:48:51] Debug: Using . as Game and Save directory

Test game needs to be re-downloaded and set up but anyway it seems there aren't speed differences between new and old version of liblcf.

**Comment by Ghabry** [comment]
That could be the filefinder. But according to your timing this means (for the testgame) a read-speed of 20 directory entries per second. That's so awful that I can't believe this.

**Comment by Rinnegatamante** [comment]
If you're talking about the 7 minutes loading. That was referred to Yume Nikki as i said.

**Comment by Ghabry** [comment]
Oh, it was late when I wrote this. I only looked at the "seconds" counter... woa, that's even worse.
That's obviously the "FileFinder", but why is this so slow, IO is sooo bad on the 3DS? o.O
Have to investigate this.

**Comment by Rinnegatamante** [comment]
Solved with https://github.com/Rinnegatamante/easyrpg-player-3ds/commit/58245a0e9ed7d60bb4d79480ce34923ffc885eec
